# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gyroid_service_pb2 as gyroid__service__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gyroid_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GyroidOptimizerStub:
    """─── Service ─────────────────────────────────────────────────────────────────

    ── Config ─────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConfig = channel.unary_unary(
                '/gyroid.GyroidOptimizer/GetConfig',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/gyroid.GyroidOptimizer/SetConfig',
                request_serializer=gyroid__service__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=gyroid__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.PatchConfig = channel.unary_unary(
                '/gyroid.GyroidOptimizer/PatchConfig',
                request_serializer=gyroid__service__pb2.PatchConfigRequest.SerializeToString,
                response_deserializer=gyroid__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StartRun = channel.unary_unary(
                '/gyroid.GyroidOptimizer/StartRun',
                request_serializer=gyroid__service__pb2.StartRunRequest.SerializeToString,
                response_deserializer=gyroid__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StopRun = channel.unary_unary(
                '/gyroid.GyroidOptimizer/StopRun',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetRunStatus = channel.unary_unary(
                '/gyroid.GyroidOptimizer/GetRunStatus',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.RunStatusResponse.FromString,
                _registered_method=True)
        self.StreamOutput = channel.unary_stream(
                '/gyroid.GyroidOptimizer/StreamOutput',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.OutputLine.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/gyroid.GyroidOptimizer/GetHistory',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.HistoryResponse.FromString,
                _registered_method=True)
        self.GetLatestMetrics = channel.unary_unary(
                '/gyroid.GyroidOptimizer/GetLatestMetrics',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.LatestMetricsResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/gyroid.GyroidOptimizer/ListFiles',
                request_serializer=gyroid__service__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=gyroid__service__pb2.FileListResponse.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/gyroid.GyroidOptimizer/DownloadFile',
                request_serializer=gyroid__service__pb2.DownloadRequest.SerializeToString,
                response_deserializer=gyroid__service__pb2.FileChunk.FromString,
                _registered_method=True)
        self.StartStlExport = channel.unary_unary(
                '/gyroid.GyroidOptimizer/StartStlExport',
                request_serializer=gyroid__service__pb2.StlExportRequest.SerializeToString,
                response_deserializer=gyroid__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StopStlExport = channel.unary_unary(
                '/gyroid.GyroidOptimizer/StopStlExport',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetStlStatus = channel.unary_unary(
                '/gyroid.GyroidOptimizer/GetStlStatus',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.RunStatusResponse.FromString,
                _registered_method=True)
        self.StreamStlOutput = channel.unary_stream(
                '/gyroid.GyroidOptimizer/StreamStlOutput',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.OutputLine.FromString,
                _registered_method=True)
        self.DownloadStl = channel.unary_stream(
                '/gyroid.GyroidOptimizer/DownloadStl',
                request_serializer=gyroid__service__pb2.StlFileRequest.SerializeToString,
                response_deserializer=gyroid__service__pb2.FileChunk.FromString,
                _registered_method=True)
        self.StartGyroidToQuadMesh = channel.unary_unary(
                '/gyroid.GyroidOptimizer/StartGyroidToQuadMesh',
                request_serializer=gyroid__service__pb2.QuadMeshRequest.SerializeToString,
                response_deserializer=gyroid__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StopGyroidToQuadMesh = channel.unary_unary(
                '/gyroid.GyroidOptimizer/StopGyroidToQuadMesh',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetGyroidToQuadMeshStatus = channel.unary_unary(
                '/gyroid.GyroidOptimizer/GetGyroidToQuadMeshStatus',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.RunStatusResponse.FromString,
                _registered_method=True)
        self.StreamGyroidToQuadMeshOutput = channel.unary_stream(
                '/gyroid.GyroidOptimizer/StreamGyroidToQuadMeshOutput',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.OutputLine.FromString,
                _registered_method=True)
        self.StartQuadToNurbs = channel.unary_unary(
                '/gyroid.GyroidOptimizer/StartQuadToNurbs',
                request_serializer=gyroid__service__pb2.QuadToNurbsRequest.SerializeToString,
                response_deserializer=gyroid__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StopQuadToNurbs = channel.unary_unary(
                '/gyroid.GyroidOptimizer/StopQuadToNurbs',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetQuadToNurbsStatus = channel.unary_unary(
                '/gyroid.GyroidOptimizer/GetQuadToNurbsStatus',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.RunStatusResponse.FromString,
                _registered_method=True)
        self.StreamQuadToNurbsOutput = channel.unary_stream(
                '/gyroid.GyroidOptimizer/StreamQuadToNurbsOutput',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.OutputLine.FromString,
                _registered_method=True)
        self.DownloadNurbsFile = channel.unary_stream(
                '/gyroid.GyroidOptimizer/DownloadNurbsFile',
                request_serializer=gyroid__service__pb2.NurbsFileRequest.SerializeToString,
                response_deserializer=gyroid__service__pb2.FileChunk.FromString,
                _registered_method=True)
        self.StartPrintPrep = channel.unary_unary(
                '/gyroid.GyroidOptimizer/StartPrintPrep',
                request_serializer=gyroid__service__pb2.PrintPrepRequest.SerializeToString,
                response_deserializer=gyroid__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StopPrintPrep = channel.unary_unary(
                '/gyroid.GyroidOptimizer/StopPrintPrep',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetPrintPrepStatus = channel.unary_unary(
                '/gyroid.GyroidOptimizer/GetPrintPrepStatus',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.RunStatusResponse.FromString,
                _registered_method=True)
        self.StreamPrintPrepOutput = channel.unary_stream(
                '/gyroid.GyroidOptimizer/StreamPrintPrepOutput',
                request_serializer=gyroid__service__pb2.Empty.SerializeToString,
                response_deserializer=gyroid__service__pb2.OutputLine.FromString,
                _registered_method=True)
        self.DownloadPrintPrepFile = channel.unary_stream(
                '/gyroid.GyroidOptimizer/DownloadPrintPrepFile',
                request_serializer=gyroid__service__pb2.PrintPrepFileRequest.SerializeToString,
                response_deserializer=gyroid__service__pb2.FileChunk.FromString,
                _registered_method=True)




class GyroidOptimizerServicer:
    """─── Service ─────────────────────────────────────────────────────────────────

    ── Config ─────────────────────────────────────────────────────────────────
    """

    def GetConfig(self, request, context):
        """Return the current gyroid_case_config.yaml content.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """Overwrite the entire config file.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PatchConfig(self, request, context):
        """Patch individual fields by dot-notation key (preserves unmentioned values
        but discards YAML comments).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRun(self, request, context):
        """── Run control ────────────────────────────────────────────────────────────

        Start gyroid_case_wrapper.py (error if already running).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRun(self, request, context):
        """Send SIGTERM to the running process (SIGKILL after 10 s).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunStatus(self, request, context):
        """Query the current process state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOutput(self, request, context):
        """── Monitoring ─────────────────────────────────────────────────────────────

        Server-streaming: replay buffered output, then tail live output.
        Terminates when the run finishes or the client disconnects.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """── Results ────────────────────────────────────────────────────────────────

        Return all rows of app/gyroid_opt_history.txt.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestMetrics(self, request, context):
        """Return only the most-recent row of the history file.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """── File access ────────────────────────────────────────────────────────────

        List files under app/ (or a subdirectory).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Stream a single file or a .tar.gz of a directory.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartStlExport(self, request, context):
        """── STL export ─────────────────────────────────────────────────────────────

        Start gyroid_to_stl.py (error if already running).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStlExport(self, request, context):
        """Send SIGTERM to the STL export process (SIGKILL after 10 s).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStlStatus(self, request, context):
        """Query the STL export process state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStlOutput(self, request, context):
        """Server-streaming: replay buffered STL-export output, then tail live output.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadStl(self, request, context):
        """Download a generated STL file (or all of them as a .tar.gz).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


    def StartGyroidToQuadMesh(self, request, context):
        """── Gyroid → quad mesh ─────────────────────────────────────────────────────

        Start gyroid_to_quad_mesh_qf.py (error if already running).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopGyroidToQuadMesh(self, request, context):
        """Send SIGTERM to the quad-mesh process (SIGKILL after 10 s).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGyroidToQuadMeshStatus(self, request, context):
        """Query the quad-mesh process state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGyroidToQuadMeshOutput(self, request, context):
        """Server-streaming: replay buffered output, then tail live output.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartQuadToNurbs(self, request, context):
        """── Quad mesh → NURBS STEP ─────────────────────────────────────────────────

        Start quad_to_nurbs.py for a specific gyroid sheet (error if already running).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopQuadToNurbs(self, request, context):
        """Send SIGTERM to the quad-to-NURBS process (SIGKILL after 10 s).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuadToNurbsStatus(self, request, context):
        """Query the quad-to-NURBS process state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamQuadToNurbsOutput(self, request, context):
        """Server-streaming: replay buffered output, then tail live output.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadNurbsFile(self, request, context):
        """Download a generated OBJ (quad mesh) or STEP (NURBS) file.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    def StartPrintPrep(self, request, context):
        """── Print preparation ──────────────────────────────────────────────────────

        Start gyroid_print_prep.py (error if already running).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopPrintPrep(self, request, context):
        """Send SIGTERM to the print-prep process (SIGKILL after 10 s).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrintPrepStatus(self, request, context):
        """Query the print-prep process state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPrintPrepOutput(self, request, context):
        """Server-streaming: replay buffered output, then tail live output.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadPrintPrepFile(self, request, context):
        """Download a generated build/overhang/supports STL file.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

def add_GyroidOptimizerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.ConfigResponse.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=gyroid__service__pb2.SetConfigRequest.FromString,
                    response_serializer=gyroid__service__pb2.StatusResponse.SerializeToString,
            ),
            'PatchConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.PatchConfig,
                    request_deserializer=gyroid__service__pb2.PatchConfigRequest.FromString,
                    response_serializer=gyroid__service__pb2.StatusResponse.SerializeToString,
            ),
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=gyroid__service__pb2.StartRunRequest.FromString,
                    response_serializer=gyroid__service__pb2.StatusResponse.SerializeToString,
            ),
            'StopRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRun,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.StatusResponse.SerializeToString,
            ),
            'GetRunStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunStatus,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.RunStatusResponse.SerializeToString,
            ),
            'StreamOutput': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOutput,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.OutputLine.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.HistoryResponse.SerializeToString,
            ),
            'GetLatestMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestMetrics,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.LatestMetricsResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=gyroid__service__pb2.ListFilesRequest.FromString,
                    response_serializer=gyroid__service__pb2.FileListResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=gyroid__service__pb2.DownloadRequest.FromString,
                    response_serializer=gyroid__service__pb2.FileChunk.SerializeToString,
            ),
            'StartStlExport': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStlExport,
                    request_deserializer=gyroid__service__pb2.StlExportRequest.FromString,
                    response_serializer=gyroid__service__pb2.StatusResponse.SerializeToString,
            ),
            'StopStlExport': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStlExport,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.StatusResponse.SerializeToString,
            ),
            'GetStlStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStlStatus,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.RunStatusResponse.SerializeToString,
            ),
            'StreamStlOutput': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStlOutput,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.OutputLine.SerializeToString,
            ),
            'DownloadStl': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadStl,
                    request_deserializer=gyroid__service__pb2.StlFileRequest.FromString,
                    response_serializer=gyroid__service__pb2.FileChunk.SerializeToString,
            ),
            'StartGyroidToQuadMesh': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGyroidToQuadMesh,
                    request_deserializer=gyroid__service__pb2.QuadMeshRequest.FromString,
                    response_serializer=gyroid__service__pb2.StatusResponse.SerializeToString,
            ),
            'StopGyroidToQuadMesh': grpc.unary_unary_rpc_method_handler(
                    servicer.StopGyroidToQuadMesh,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.StatusResponse.SerializeToString,
            ),
            'GetGyroidToQuadMeshStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGyroidToQuadMeshStatus,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.RunStatusResponse.SerializeToString,
            ),
            'StreamGyroidToQuadMeshOutput': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGyroidToQuadMeshOutput,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.OutputLine.SerializeToString,
            ),
            'StartQuadToNurbs': grpc.unary_unary_rpc_method_handler(
                    servicer.StartQuadToNurbs,
                    request_deserializer=gyroid__service__pb2.QuadToNurbsRequest.FromString,
                    response_serializer=gyroid__service__pb2.StatusResponse.SerializeToString,
            ),
            'StopQuadToNurbs': grpc.unary_unary_rpc_method_handler(
                    servicer.StopQuadToNurbs,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.StatusResponse.SerializeToString,
            ),
            'GetQuadToNurbsStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuadToNurbsStatus,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.RunStatusResponse.SerializeToString,
            ),
            'StreamQuadToNurbsOutput': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamQuadToNurbsOutput,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.OutputLine.SerializeToString,
            ),
            'DownloadNurbsFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadNurbsFile,
                    request_deserializer=gyroid__service__pb2.NurbsFileRequest.FromString,
                    response_serializer=gyroid__service__pb2.FileChunk.SerializeToString,
            ),
            'StartPrintPrep': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPrintPrep,
                    request_deserializer=gyroid__service__pb2.PrintPrepRequest.FromString,
                    response_serializer=gyroid__service__pb2.StatusResponse.SerializeToString,
            ),
            'StopPrintPrep': grpc.unary_unary_rpc_method_handler(
                    servicer.StopPrintPrep,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.StatusResponse.SerializeToString,
            ),
            'GetPrintPrepStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrintPrepStatus,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.RunStatusResponse.SerializeToString,
            ),
            'StreamPrintPrepOutput': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPrintPrepOutput,
                    request_deserializer=gyroid__service__pb2.Empty.FromString,
                    response_serializer=gyroid__service__pb2.OutputLine.SerializeToString,
            ),
            'DownloadPrintPrepFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadPrintPrepFile,
                    request_deserializer=gyroid__service__pb2.PrintPrepFileRequest.FromString,
                    response_serializer=gyroid__service__pb2.FileChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gyroid.GyroidOptimizer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gyroid.GyroidOptimizer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GyroidOptimizer:
    """─── Service ─────────────────────────────────────────────────────────────────

    ── Config ─────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/GetConfig',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/SetConfig',
            gyroid__service__pb2.SetConfigRequest.SerializeToString,
            gyroid__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PatchConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/PatchConfig',
            gyroid__service__pb2.PatchConfigRequest.SerializeToString,
            gyroid__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/StartRun',
            gyroid__service__pb2.StartRunRequest.SerializeToString,
            gyroid__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/StopRun',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/GetRunStatus',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.RunStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gyroid.GyroidOptimizer/StreamOutput',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.OutputLine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/GetHistory',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/GetLatestMetrics',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.LatestMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/ListFiles',
            gyroid__service__pb2.ListFilesRequest.SerializeToString,
            gyroid__service__pb2.FileListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gyroid.GyroidOptimizer/DownloadFile',
            gyroid__service__pb2.DownloadRequest.SerializeToString,
            gyroid__service__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartStlExport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/StartStlExport',
            gyroid__service__pb2.StlExportRequest.SerializeToString,
            gyroid__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopStlExport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/StopStlExport',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStlStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/GetStlStatus',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.RunStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStlOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gyroid.GyroidOptimizer/StreamStlOutput',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.OutputLine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadStl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gyroid.GyroidOptimizer/DownloadStl',
            gyroid__service__pb2.StlFileRequest.SerializeToString,
            gyroid__service__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartGyroidToQuadMesh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/StartGyroidToQuadMesh',
            gyroid__service__pb2.QuadMeshRequest.SerializeToString,
            gyroid__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopGyroidToQuadMesh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/StopGyroidToQuadMesh',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGyroidToQuadMeshStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/GetGyroidToQuadMeshStatus',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.RunStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGyroidToQuadMeshOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gyroid.GyroidOptimizer/StreamGyroidToQuadMeshOutput',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.OutputLine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartQuadToNurbs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/StartQuadToNurbs',
            gyroid__service__pb2.QuadToNurbsRequest.SerializeToString,
            gyroid__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopQuadToNurbs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/StopQuadToNurbs',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuadToNurbsStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/GetQuadToNurbsStatus',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.RunStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamQuadToNurbsOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gyroid.GyroidOptimizer/StreamQuadToNurbsOutput',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.OutputLine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadNurbsFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gyroid.GyroidOptimizer/DownloadNurbsFile',
            gyroid__service__pb2.NurbsFileRequest.SerializeToString,
            gyroid__service__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartPrintPrep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/StartPrintPrep',
            gyroid__service__pb2.PrintPrepRequest.SerializeToString,
            gyroid__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopPrintPrep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/StopPrintPrep',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrintPrepStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gyroid.GyroidOptimizer/GetPrintPrepStatus',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.RunStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPrintPrepOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gyroid.GyroidOptimizer/StreamPrintPrepOutput',
            gyroid__service__pb2.Empty.SerializeToString,
            gyroid__service__pb2.OutputLine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadPrintPrepFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gyroid.GyroidOptimizer/DownloadPrintPrepFile',
            gyroid__service__pb2.PrintPrepFileRequest.SerializeToString,
            gyroid__service__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
